### ISSUE TITLE
Extend arrow not showing up on colorbar

### ISSUE THREAD

**Issue by DaniJonesOcean** [DanJonesOcean/expose-tracer#5]
I would like there to be an "extend" arrow on the colorbar, showing that the scale continues past 0.6. However, so far it will not display.

**Comment by DanJonesOcean** [comment]
I put this issue on StackOverflow and received a helpful reply very quickly:

https://stackoverflow.com/questions/67720032/use-of-extend-in-a-contourf-plot-with-a-discrete-colorbar-not-working

All fixed!
